plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'leisure'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}


ext {
    set('jjwtVersion', '0.12.6')
    set('p6spyVersion','2.0.1')
}

dependencies {
    // Spring MVC
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Spring OAuth2
    // implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // Password Hashing
    // implementation 'org.springframework.security:spring-security-crypto'

    // JWT
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    runtimeOnly   "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    runtimeOnly   "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Database Driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // JPAs
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // p6spy
    implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:${p6spyVersion}"

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    description = '단위 테스트'
    useJUnitPlatform {
        excludeTags 'integration'
    }
    testLogging {
        events "failed"
        exceptionFormat = "full"
        showStandardStreams = true
    }
}

tasks.register('integrationTest', Test) {
    description = '통합 테스트'
    group = 'verification'
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    useJUnitPlatform {
        includeTags 'integration'
    }
    shouldRunAfter tasks.named('test')
    testLogging {
        events "failed"
        exceptionFormat = "full"
        showStandardStreams = true
    }
}