# application.yml
# 모든 환경에서 공통으로 적용되는 기본 설정 파일

spring:
  application:
    name: leisure        # 애플리케이션 이름
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

rabbitmq:
  domain-exchange: domain.events
  dead-letter-exchange: domain.events.dlx
  api-queue: api.domain.events.queue
  api-dlq: api.domain.events.dlq

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 사용할 DB 방언(MySQL 문법에 맞게 SQL 생성)
        format_sql: true                             # 출력되는 SQL을 보기 좋게 줄바꿈/들여쓰기
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul

  open-in-view: false    # OSIV 끔 → 영속성 컨텍스트를 트랜잭션 범위로 제한

swagger:
  servers:
    local: http://localhost:8080